$ErrorActionPreference = "Stop"
Set-Location -LiteralPath $PSScriptRoot

$env:PGHOST = "192.168.1.245"
$env:PGPORT = "5432"
$env:PGDATABASE = "inss_clientes_teste"
$env:PGUSER = "postgres"
$env:PGPASSWORD = "651010"
$env:APP_HOST = "0.0.0.0"
$env:APP_PORT = "8001"
$env:APP_ENABLE_CEP_ENRICHMENT = "1"
$env:APP_ENABLE_DDD_ENRICHMENT = "1"
$env:APP_ENABLE_STARTUP_SCHEMA_MAINTENANCE = "0"
$env:APP_ENABLE_STARTUP_ADDRESS_BACKFILL = "1"
$env:FACTA_HOMOLOG_BASE = "https://webservice-homol.facta.com.br"
$env:FACTA_OFFLINE_BASE = "https://cltoff.facta.com.br"
$env:FACTA_USERNAME = "98078"
$env:FACTA_PASSWORD = "t6sc9tzztyju0ro591st"
$env:C6_WORKER_ENABLED = "true"
$env:C6_BASE_URL = "https://marketplace-proposal-service-api-p.c6bank.info"
$env:C6_USERNAME = "01278252584_003238"
$env:C6_PASSWORD = "Brasil@2026"
$env:C6_TIMEOUT_SECONDS = "20"

Write-Host "Ambiente de TESTE"
Write-Host "PGHOST=$env:PGHOST"
Write-Host "PGPORT=$env:PGPORT"
Write-Host "PGDATABASE=$env:PGDATABASE"
Write-Host "PGUSER=$env:PGUSER"
Write-Host "APP_PORT=$env:APP_PORT"
Write-Host "APP_ENABLE_CEP_ENRICHMENT=$env:APP_ENABLE_CEP_ENRICHMENT"
Write-Host "APP_ENABLE_DDD_ENRICHMENT=$env:APP_ENABLE_DDD_ENRICHMENT"
Write-Host "APP_ENABLE_STARTUP_SCHEMA_MAINTENANCE=$env:APP_ENABLE_STARTUP_SCHEMA_MAINTENANCE"
Write-Host "APP_ENABLE_STARTUP_ADDRESS_BACKFILL=$env:APP_ENABLE_STARTUP_ADDRESS_BACKFILL"
Write-Host "C6_WORKER_ENABLED=$env:C6_WORKER_ENABLED"
Write-Host "ROOT=$PSScriptRoot"
Write-Host ""

& "C:\Python312\python.exe" (Join-Path $PSScriptRoot "run_inss_app.py")
