@echo off
cd /d "\\Win-7bicsiu84ik\d\DADOS\PEDRO FILTRAGEM\ANALISE DE DADOS\BANCO_CLIENTES_INSS"
"\\Win-7bicsiu84ik\d\DADOS\PEDRO FILTRAGEM\ANALISE DE DADOS\BANCO_CLIENTES_INSS\.venv\Scripts\python.exe" "\\Win-7bicsiu84ik\d\DADOS\PEDRO FILTRAGEM\ANALISE DE DADOS\BANCO_CLIENTES_INSS\run_inss_app.py" >> "\\Win-7bicsiu84ik\d\DADOS\PEDRO FILTRAGEM\ANALISE DE DADOS\BANCO_CLIENTES_INSS\logs\autostart.out.log" 2>> "\\Win-7bicsiu84ik\d\DADOS\PEDRO FILTRAGEM\ANALISE DE DADOS\BANCO_CLIENTES_INSS\logs\autostart.err.log"
